# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  battleshipapi:
    image: battleshipapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:2000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
